(ns othello.rules-spec
  (:require [speclj.core :refer :all]
            [othello.board :as board]
            [othello.rules :as rules]
            [othello.spec-helper :refer [parse-board]]))

(def opening (board/initial-board))

(describe "rules"
  (context "opening"
    (it "gives black four legal opening moves"
      (should= [[2 3] [3 2] [4 5] [5 4]]
               (rules/legal-moves opening board/black)))

    (it "gives white the four mirrored opening moves"
      (should= [[2 4] [3 5] [4 2] [5 3]]
               (rules/legal-moves opening board/white)))

    (it "flips the sandwiched white disc on d3"
      (should= [[3 3]] (rules/flips opening board/black 2 3)))

    (it "flips the sandwiched white disc on c4"
      (should= [[3 3]] (rules/flips opening board/black 3 2)))

    (it "flips the sandwiched white disc on f5"
      (should= [[4 4]] (rules/flips opening board/black 4 5)))

    (it "flips the sandwiched white disc on e6"
      (should= [[4 4]] (rules/flips opening board/black 5 4)))

    (it "rejects occupied squares"
      (should-not (rules/legal? opening board/black 3 3))
      (should-not (rules/legal? opening board/black 3 4))
      (should= [] (rules/flips opening board/black 3 3)))

    (it "rejects empty squares that do not sandwich"
      (should-not (rules/legal? opening board/black 0 0))
      (should-not (rules/legal? opening board/black 2 2))
      (should= [] (rules/flips opening board/black 2 4))))

  (context "apply-move"
    (it "places the disc and flips the captured line"
      (let [next (rules/apply-move opening board/black 2 3)]
        (should= board/black (board/cell next 2 3))
        (should= board/black (board/cell next 3 3))
        (should= board/black (board/cell next 3 4))
        (should= board/black (board/cell next 4 3))
        (should= board/white (board/cell next 4 4))
        (should= 4 (board/count-player next board/black))
        (should= 1 (board/count-player next board/white)))))

  (context "rays in every direction"
    (it "flips north"
      (let [b (parse-board
                "........
                 ...w....
                 ...b....
                 ........
                 ........
                 ........
                 ........
                 ........")]
        (should= [[1 3]] (rules/flips b board/black 0 3))))

    (it "flips south"
      (let [b (parse-board
                "........
                 ...b....
                 ...w....
                 ........
                 ........
                 ........
                 ........
                 ........")]
        (should= [[2 3]] (rules/flips b board/black 3 3))))

    (it "flips west"
      (let [b (parse-board
                "........
                 ........
                 .bww....
                 ........
                 ........
                 ........
                 ........
                 ........")]
        (should= [[2 3] [2 2]] (rules/flips b board/black 2 4))))

    (it "flips east"
      (let [b (parse-board
                "........
                 ........
                 ....wwb.
                 ........
                 ........
                 ........
                 ........
                 ........")]
        (should= [[2 4] [2 5]] (rules/flips b board/black 2 3))))

    (it "flips northwest"
      (let [b (parse-board
                "b.......
                 .w......
                 ........
                 ........
                 ........
                 ........
                 ........
                 ........")]
        (should= [[1 1]] (rules/flips b board/black 2 2))))

    (it "flips northeast"
      (let [b (parse-board
                ".......b
                 ......w.
                 ........
                 ........
                 ........
                 ........
                 ........
                 ........")]
        (should= [[1 6]] (rules/flips b board/black 2 5))))

    (it "flips southwest"
      (let [b (parse-board
                "........
                 ........
                 ........
                 ........
                 ........
                 ........
                 .w......
                 b.......")]
        (should= [[6 1]] (rules/flips b board/black 5 2))))

    (it "flips southeast"
      (let [b (parse-board
                "........
                 ........
                 ........
                 ........
                 ........
                 ........
                 ......w.
                 .......b")]
        (should= [[6 6]] (rules/flips b board/black 5 5))))

    (it "stops at the edge without a closing disc"
      (let [b (parse-board
                "........
                 wwwwwwww
                 ........
                 ........
                 ........
                 ........
                 ........
                 ........")]
        (should= [] (rules/flips b board/black 0 3))))

    (it "does not flip an adjacent friendly disc"
      (let [b (parse-board
                "........
                 ...b....
                 ........
                 ........
                 ........
                 ........
                 ........
                 ........")]
        (should= [] (rules/flips b board/black 0 3)))))

  (context "game over and winner"
    (it "is over when neither player can move"
      (let [b (parse-board
                "bbbbbbbb
                 bbbbbbbb
                 bbbbbbbb
                 bbbbbbbb
                 wwwwwwww
                 wwwwwwww
                 wwwwwwww
                 wwwwwwww")]
        (should (rules/game-over? b))
        (should-not (rules/has-move? b board/black))
        (should-not (rules/has-move? b board/white))
        (should= :draw (rules/winner b))))

    (it "names black the winner when black has more discs"
      (let [b (parse-board
                "bbbbbbbb
                 bbbbbbbb
                 bbbbbbbb
                 bbbbbbbb
                 bbbbbbbb
                 wwwwwwww
                 wwwwwwww
                 wwwwwwww")]
        (should= board/black (rules/winner b))))

    (it "names white the winner when white has more discs"
      (let [b (parse-board
                "bbbbbbbb
                 bbbbbbbb
                 bbbbbbbb
                 wwwwwwww
                 wwwwwwww
                 wwwwwwww
                 wwwwwwww
                 wwwwwwww")]
        (should= board/white (rules/winner b))))

    (it "is not over at the opening"
      (should-not (rules/game-over? opening))
      (should (rules/has-move? opening board/black)))))
